module Constants

    ## Constants::KEYHOLDER_SMALLでアクセスする
    KEYHOLDER_SMALL = 190
    KEYHOLDER_MEDIUM = 240
    KEYHOLDER_LARGE = 260
    KEYHOLDER_EXTRA = 290
    KEYHOLDER_SMALL_AB = 250
    KEYHOLDER_MEDIUM_AB = 290
    KEYHOLDER_LARGE_AB = 320
    KEYHOLDER_EXTRA_AB = 350
    COASTER = 190

    TAX = 1.08

    WRAP_UNIT_1 = 8

    CARRIAGE = 350

end